/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as TrackOrderIdRouteImport } from './routes/track.$orderId'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppShiftsRouteImport } from './routes/app.shifts'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRecipesRouteImport } from './routes/app.recipes'
import { Route as AppPurchaseOrdersRouteImport } from './routes/app.purchase-orders'
import { Route as AppPromosRouteImport } from './routes/app.promos'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppOnlineOrdersRouteImport } from './routes/app.online-orders'
import { Route as AppMenuRouteImport } from './routes/app.menu'
import { Route as AppLoyaltyRouteImport } from './routes/app.loyalty'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppDeliveryRouteImport } from './routes/app.delivery'
import { Route as AppCouriersRouteImport } from './routes/app.couriers'
import { Route as AppCourierRouteImport } from './routes/app.courier'
import { Route as AppCategoriesRouteImport } from './routes/app.categories'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as SSlugIndexRouteImport } from './routes/s.$slug.index'
import { Route as SSlugOrdersRouteImport } from './routes/s.$slug.orders'
import { Route as SSlugLoginRouteImport } from './routes/s.$slug.login'
import { Route as SSlugCheckoutRouteImport } from './routes/s.$slug.checkout'
import { Route as SSlugCartRouteImport } from './routes/s.$slug.cart'
import { Route as SSlugPayOrderIdRouteImport } from './routes/s.$slug.pay.$orderId'
import { Route as SSlugMenuMenuIdRouteImport } from './routes/s.$slug.menu.$menuId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TrackOrderIdRoute = TrackOrderIdRouteImport.update({
  id: '/track/$orderId',
  path: '/track/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPromosRoute = AppPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppOnlineOrdersRoute = AppOnlineOrdersRouteImport.update({
  id: '/online-orders',
  path: '/online-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppLoyaltyRoute = AppLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveryRoute = AppDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AppRoute,
} as any)
const AppCouriersRoute = AppCouriersRouteImport.update({
  id: '/couriers',
  path: '/couriers',
  getParentRoute: () => AppRoute,
} as any)
const AppCourierRoute = AppCourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const SSlugIndexRoute = SSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugOrdersRoute = SSlugOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugLoginRoute = SSlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugCheckoutRoute = SSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugCartRoute = SSlugCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugPayOrderIdRoute = SSlugPayOrderIdRouteImport.update({
  id: '/pay/$orderId',
  path: '/pay/$orderId',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugMenuMenuIdRoute = SSlugMenuMenuIdRouteImport.update({
  id: '/menu/$menuId',
  path: '/menu/$menuId',
  getParentRoute: () => SSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/courier': typeof AppCourierRoute
  '/app/couriers': typeof AppCouriersRoute
  '/app/delivery': typeof AppDeliveryRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/menu': typeof AppMenuRoute
  '/app/online-orders': typeof AppOnlineOrdersRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/pos': typeof AppPosRoute
  '/app/promos': typeof AppPromosRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/recipes': typeof AppRecipesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/track/$orderId': typeof TrackOrderIdRoute
  '/app/': typeof AppIndexRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/login': typeof SSlugLoginRoute
  '/s/$slug/orders': typeof SSlugOrdersRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/s/$slug/menu/$menuId': typeof SSlugMenuMenuIdRoute
  '/s/$slug/pay/$orderId': typeof SSlugPayOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/courier': typeof AppCourierRoute
  '/app/couriers': typeof AppCouriersRoute
  '/app/delivery': typeof AppDeliveryRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/menu': typeof AppMenuRoute
  '/app/online-orders': typeof AppOnlineOrdersRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/pos': typeof AppPosRoute
  '/app/promos': typeof AppPromosRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/recipes': typeof AppRecipesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/track/$orderId': typeof TrackOrderIdRoute
  '/app': typeof AppIndexRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/login': typeof SSlugLoginRoute
  '/s/$slug/orders': typeof SSlugOrdersRoute
  '/s/$slug': typeof SSlugIndexRoute
  '/s/$slug/menu/$menuId': typeof SSlugMenuMenuIdRoute
  '/s/$slug/pay/$orderId': typeof SSlugPayOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/courier': typeof AppCourierRoute
  '/app/couriers': typeof AppCouriersRoute
  '/app/delivery': typeof AppDeliveryRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/loyalty': typeof AppLoyaltyRoute
  '/app/menu': typeof AppMenuRoute
  '/app/online-orders': typeof AppOnlineOrdersRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/pos': typeof AppPosRoute
  '/app/promos': typeof AppPromosRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/recipes': typeof AppRecipesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/track/$orderId': typeof TrackOrderIdRoute
  '/app/': typeof AppIndexRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/checkout': typeof SSlugCheckoutRoute
  '/s/$slug/login': typeof SSlugLoginRoute
  '/s/$slug/orders': typeof SSlugOrdersRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/s/$slug/menu/$menuId': typeof SSlugMenuMenuIdRoute
  '/s/$slug/pay/$orderId': typeof SSlugPayOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/attendance'
    | '/app/categories'
    | '/app/courier'
    | '/app/couriers'
    | '/app/delivery'
    | '/app/employees'
    | '/app/inventory'
    | '/app/loyalty'
    | '/app/menu'
    | '/app/online-orders'
    | '/app/orders'
    | '/app/pos'
    | '/app/promos'
    | '/app/purchase-orders'
    | '/app/recipes'
    | '/app/reports'
    | '/app/schedule'
    | '/app/settings'
    | '/app/shifts'
    | '/app/suppliers'
    | '/invite/$token'
    | '/s/$slug'
    | '/track/$orderId'
    | '/app/'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/login'
    | '/s/$slug/orders'
    | '/s/$slug/'
    | '/s/$slug/menu/$menuId'
    | '/s/$slug/pay/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/attendance'
    | '/app/categories'
    | '/app/courier'
    | '/app/couriers'
    | '/app/delivery'
    | '/app/employees'
    | '/app/inventory'
    | '/app/loyalty'
    | '/app/menu'
    | '/app/online-orders'
    | '/app/orders'
    | '/app/pos'
    | '/app/promos'
    | '/app/purchase-orders'
    | '/app/recipes'
    | '/app/reports'
    | '/app/schedule'
    | '/app/settings'
    | '/app/shifts'
    | '/app/suppliers'
    | '/invite/$token'
    | '/track/$orderId'
    | '/app'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/login'
    | '/s/$slug/orders'
    | '/s/$slug'
    | '/s/$slug/menu/$menuId'
    | '/s/$slug/pay/$orderId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/attendance'
    | '/app/categories'
    | '/app/courier'
    | '/app/couriers'
    | '/app/delivery'
    | '/app/employees'
    | '/app/inventory'
    | '/app/loyalty'
    | '/app/menu'
    | '/app/online-orders'
    | '/app/orders'
    | '/app/pos'
    | '/app/promos'
    | '/app/purchase-orders'
    | '/app/recipes'
    | '/app/reports'
    | '/app/schedule'
    | '/app/settings'
    | '/app/shifts'
    | '/app/suppliers'
    | '/invite/$token'
    | '/s/$slug'
    | '/track/$orderId'
    | '/app/'
    | '/s/$slug/cart'
    | '/s/$slug/checkout'
    | '/s/$slug/login'
    | '/s/$slug/orders'
    | '/s/$slug/'
    | '/s/$slug/menu/$menuId'
    | '/s/$slug/pay/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SSlugRoute: typeof SSlugRouteWithChildren
  TrackOrderIdRoute: typeof TrackOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/track/$orderId': {
      id: '/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/track/$orderId'
      preLoaderRoute: typeof TrackOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shifts': {
      id: '/app/shifts'
      path: '/shifts'
      fullPath: '/app/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recipes': {
      id: '/app/recipes'
      path: '/recipes'
      fullPath: '/app/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders': {
      id: '/app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/promos': {
      id: '/app/promos'
      path: '/promos'
      fullPath: '/app/promos'
      preLoaderRoute: typeof AppPromosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/online-orders': {
      id: '/app/online-orders'
      path: '/online-orders'
      fullPath: '/app/online-orders'
      preLoaderRoute: typeof AppOnlineOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/menu': {
      id: '/app/menu'
      path: '/menu'
      fullPath: '/app/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/loyalty': {
      id: '/app/loyalty'
      path: '/loyalty'
      fullPath: '/app/loyalty'
      preLoaderRoute: typeof AppLoyaltyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/delivery': {
      id: '/app/delivery'
      path: '/delivery'
      fullPath: '/app/delivery'
      preLoaderRoute: typeof AppDeliveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/couriers': {
      id: '/app/couriers'
      path: '/couriers'
      fullPath: '/app/couriers'
      preLoaderRoute: typeof AppCouriersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courier': {
      id: '/app/courier'
      path: '/courier'
      fullPath: '/app/courier'
      preLoaderRoute: typeof AppCourierRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/s/$slug/': {
      id: '/s/$slug/'
      path: '/'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof SSlugIndexRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/orders': {
      id: '/s/$slug/orders'
      path: '/orders'
      fullPath: '/s/$slug/orders'
      preLoaderRoute: typeof SSlugOrdersRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/login': {
      id: '/s/$slug/login'
      path: '/login'
      fullPath: '/s/$slug/login'
      preLoaderRoute: typeof SSlugLoginRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/checkout': {
      id: '/s/$slug/checkout'
      path: '/checkout'
      fullPath: '/s/$slug/checkout'
      preLoaderRoute: typeof SSlugCheckoutRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/cart': {
      id: '/s/$slug/cart'
      path: '/cart'
      fullPath: '/s/$slug/cart'
      preLoaderRoute: typeof SSlugCartRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/pay/$orderId': {
      id: '/s/$slug/pay/$orderId'
      path: '/pay/$orderId'
      fullPath: '/s/$slug/pay/$orderId'
      preLoaderRoute: typeof SSlugPayOrderIdRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/menu/$menuId': {
      id: '/s/$slug/menu/$menuId'
      path: '/menu/$menuId'
      fullPath: '/s/$slug/menu/$menuId'
      preLoaderRoute: typeof SSlugMenuMenuIdRouteImport
      parentRoute: typeof SSlugRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCourierRoute: typeof AppCourierRoute
  AppCouriersRoute: typeof AppCouriersRoute
  AppDeliveryRoute: typeof AppDeliveryRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLoyaltyRoute: typeof AppLoyaltyRoute
  AppMenuRoute: typeof AppMenuRoute
  AppOnlineOrdersRoute: typeof AppOnlineOrdersRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPosRoute: typeof AppPosRoute
  AppPromosRoute: typeof AppPromosRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppRecipesRoute: typeof AppRecipesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShiftsRoute: typeof AppShiftsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCourierRoute: AppCourierRoute,
  AppCouriersRoute: AppCouriersRoute,
  AppDeliveryRoute: AppDeliveryRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLoyaltyRoute: AppLoyaltyRoute,
  AppMenuRoute: AppMenuRoute,
  AppOnlineOrdersRoute: AppOnlineOrdersRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPosRoute: AppPosRoute,
  AppPromosRoute: AppPromosRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppRecipesRoute: AppRecipesRoute,
  AppReportsRoute: AppReportsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShiftsRoute: AppShiftsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SSlugRouteChildren {
  SSlugCartRoute: typeof SSlugCartRoute
  SSlugCheckoutRoute: typeof SSlugCheckoutRoute
  SSlugLoginRoute: typeof SSlugLoginRoute
  SSlugOrdersRoute: typeof SSlugOrdersRoute
  SSlugIndexRoute: typeof SSlugIndexRoute
  SSlugMenuMenuIdRoute: typeof SSlugMenuMenuIdRoute
  SSlugPayOrderIdRoute: typeof SSlugPayOrderIdRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugCartRoute: SSlugCartRoute,
  SSlugCheckoutRoute: SSlugCheckoutRoute,
  SSlugLoginRoute: SSlugLoginRoute,
  SSlugOrdersRoute: SSlugOrdersRoute,
  SSlugIndexRoute: SSlugIndexRoute,
  SSlugMenuMenuIdRoute: SSlugMenuMenuIdRoute,
  SSlugPayOrderIdRoute: SSlugPayOrderIdRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  SSlugRoute: SSlugRouteWithChildren,
  TrackOrderIdRoute: TrackOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
