/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRecipesRouteImport } from './routes/app.recipes'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppMenuRouteImport } from './routes/app.menu'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppCategoriesRouteImport } from './routes/app.categories'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as SSlugIndexRouteImport } from './routes/s.$slug.index'
import { Route as SSlugCartRouteImport } from './routes/s.$slug.cart'
import { Route as SSlugMenuMenuIdRouteImport } from './routes/s.$slug.menu.$menuId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const SSlugIndexRoute = SSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugCartRoute = SSlugCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugMenuMenuIdRoute = SSlugMenuMenuIdRouteImport.update({
  id: '/menu/$menuId',
  path: '/menu/$menuId',
  getParentRoute: () => SSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/menu': typeof AppMenuRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/pos': typeof AppPosRoute
  '/app/recipes': typeof AppRecipesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/invite/$token': typeof InviteTokenRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/s/$slug/menu/$menuId': typeof SSlugMenuMenuIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/menu': typeof AppMenuRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/pos': typeof AppPosRoute
  '/app/recipes': typeof AppRecipesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app': typeof AppIndexRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug': typeof SSlugIndexRoute
  '/s/$slug/menu/$menuId': typeof SSlugMenuMenuIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/menu': typeof AppMenuRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/pos': typeof AppPosRoute
  '/app/recipes': typeof AppRecipesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/invite/$token': typeof InviteTokenRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/s/$slug/cart': typeof SSlugCartRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/s/$slug/menu/$menuId': typeof SSlugMenuMenuIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/attendance'
    | '/app/categories'
    | '/app/employees'
    | '/app/inventory'
    | '/app/menu'
    | '/app/orders'
    | '/app/pos'
    | '/app/recipes'
    | '/app/reports'
    | '/app/schedule'
    | '/invite/$token'
    | '/s/$slug'
    | '/app/'
    | '/s/$slug/cart'
    | '/s/$slug/'
    | '/s/$slug/menu/$menuId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/attendance'
    | '/app/categories'
    | '/app/employees'
    | '/app/inventory'
    | '/app/menu'
    | '/app/orders'
    | '/app/pos'
    | '/app/recipes'
    | '/app/reports'
    | '/app/schedule'
    | '/invite/$token'
    | '/app'
    | '/s/$slug/cart'
    | '/s/$slug'
    | '/s/$slug/menu/$menuId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/attendance'
    | '/app/categories'
    | '/app/employees'
    | '/app/inventory'
    | '/app/menu'
    | '/app/orders'
    | '/app/pos'
    | '/app/recipes'
    | '/app/reports'
    | '/app/schedule'
    | '/invite/$token'
    | '/s/$slug'
    | '/app/'
    | '/s/$slug/cart'
    | '/s/$slug/'
    | '/s/$slug/menu/$menuId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SSlugRoute: typeof SSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recipes': {
      id: '/app/recipes'
      path: '/recipes'
      fullPath: '/app/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/menu': {
      id: '/app/menu'
      path: '/menu'
      fullPath: '/app/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/s/$slug/': {
      id: '/s/$slug/'
      path: '/'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof SSlugIndexRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/cart': {
      id: '/s/$slug/cart'
      path: '/cart'
      fullPath: '/s/$slug/cart'
      preLoaderRoute: typeof SSlugCartRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/menu/$menuId': {
      id: '/s/$slug/menu/$menuId'
      path: '/menu/$menuId'
      fullPath: '/s/$slug/menu/$menuId'
      preLoaderRoute: typeof SSlugMenuMenuIdRouteImport
      parentRoute: typeof SSlugRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMenuRoute: typeof AppMenuRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPosRoute: typeof AppPosRoute
  AppRecipesRoute: typeof AppRecipesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMenuRoute: AppMenuRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPosRoute: AppPosRoute,
  AppRecipesRoute: AppRecipesRoute,
  AppReportsRoute: AppReportsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SSlugRouteChildren {
  SSlugCartRoute: typeof SSlugCartRoute
  SSlugIndexRoute: typeof SSlugIndexRoute
  SSlugMenuMenuIdRoute: typeof SSlugMenuMenuIdRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugCartRoute: SSlugCartRoute,
  SSlugIndexRoute: SSlugIndexRoute,
  SSlugMenuMenuIdRoute: SSlugMenuMenuIdRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  SSlugRoute: SSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
